version: "3.9"
   
services:
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py runserver 0.0.0.0:8030
    volumes:
      - .:/code
    ports:
      - "8030:8030"
    restart: on-failure

